name: 'Create release'
description: 'Create release'
inputs:
  github_token:
    description: 'Github Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create release
      id: release
      shell: bash
      run: |
        sha_short=$(git rev-parse --short HEAD)
        release_name="ArgoCD-$(date +%Y%m%d%H%M%S)"
        hub release create -m $release_name \
          -m "Hey 👋! This is a Release 🚀!
          release-version: '$release_name'" \
          -t "${{ github.sha }}" \
          $release_name
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
