name: 'Check date within range'
description: 'Check if a date is within a time range'
inputs:
  initial_hour:
    description: 'Initial hour'
    required: false
    type: string
  final_hour:
    description: 'Final hour'
    required: false
    type: string
  days:
    description: 'Days of the week allowed'
    required: false
    type: string
    default: '["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]'
outputs:
  is_within_range:
    value: ${{ steps.check_date_allowed.outputs.is_within_range }}
runs:
  using: "composite"
  steps:
    - name: Check if date is within range
      id: check_date_allowed
      shell: bash
      run: |
        # Check if the current day of the week is within the range
        day=$(date +%A | tr '[:upper:]' '[:lower:]')
        days=$(echo '${{ inputs.days }}' | tr '[:upper:]' '[:lower:]')
        echo $days
        if [[ $days != *\"$day\"* ]]; then
          echo "is_within_range=false" >> "$GITHUB_OUTPUT"
          echo '⚠️ Date of the week is not within the range. Allowed days: ${{ inputs.days }}'
          exit 0;
        fi
        # Check if the current time is within the hours specified
        current_time=$(date +%H:%M)
        if [[ $current_time < "${{ inputs.initial_hour }}" || $current_time > "${{ inputs.final_hour }}" ]]; then
          echo "is_within_range=false" >> "$GITHUB_OUTPUT"
          echo '⚠️ Date is not within the range ${{ inputs.initial_hour }} - ${{ inputs.final_hour }}'
          exit 0;
        fi
        echo "is_within_range=true" >> "$GITHUB_OUTPUT"
