name: Create release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Create release
        uses: ./.github/actions/create-release
        with:
          github_token: ${{ github.token }}
