name: Create release

on:
  workflow_dispatch:
    inputs:
      destination_buckets:
        type: string
        required: true

jobs:
  create_release:
    strategy: 
        matrix:
            bucket: ${{ fromJSON(inputs.destination_buckets) }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
