name: Create release

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Create release
        uses: ./.github/actions/create-release
        with:
          github_token: ${{ github.token }}
