name: Hotfix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: |
          git pull
          git push origin HEAD:release
      - run: gh workflow disable create_release.yml --repo mknet3/gh_actions
