name: Hotfix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - run: gh workflow disable create_release.yml --repo mknet3/gh_actions || true
        env:
          GH_TOKEN: ${{ github.token }}

      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git pull
          git checkout release
          git rebase main
          git push origin release


      - name: Update environment variable
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.updateRepoVariable({
              owner: 'mknet3',
              repo: 'gh_actions',
              name: 'HOTFIX_IN_PROGRESS',
              value: 'true',
            });

      - run: |
          gh workflow enable create_release.yml --repo mknet3/gh_actions
          gh workflow run create_release.yml --repo mknet3/gh_actions
          gh workflow disable create_release.yml --repo mknet3/gh_actions
        env:
          GH_TOKEN: ${{ github.token }}
