name: Hotfix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - run: gh workflow disable create_release.yml --repo mknet3/gh_actions || true
        env:
          GH_TOKEN: ${{ github.token }}

      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git pull
          git checkout release
          git rebase main
          git push origin release


      - name: Update environment variable
        uses: actions/github-script@v4
        with:
          script: |
            const core = require('@actions/core');
            const octokit = require('@octokit/rest')();
            octokit.authenticate({
              type: 'token',
              token: process.env.GITHUB_TOKEN
            });
            octokit.rest.actions.updateRepoVariable({
              'mknet3',
              'gh_actions',
              'HOTFIX_IN_PROGRESS',
              'true',
            });

      - run: |
          gh workflow enable create_release.yml --repo mknet3/gh_actions
          gh workflow run create_release.yml --repo mknet3/gh_actions
          gh workflow disable create_release.yml --repo mknet3/gh_actions
        env:
          GH_TOKEN: ${{ github.token }}
