name: Hotfix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: |
          git pull origin main
          git fetch origin release
          git checkout release
          git merge --allow-unrelated-histories main
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - run: gh workflow disable create_release.yml --repo mknet3/gh_actions
