name: Test labels

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Post to a Slack channel
        run: echo ${{ join(',', github.event.pull_request.labels.*.name) }}

