name: Test labels

on:
  issue_comment:
    types: [created, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Post to a Slack channel
        run: |
          echo ${{ github.event.issue.pull_request.comment }}

