name: Test labels

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Post to a Slack channel
        run: |
          for ELEMENT in ${${{ github.event.pull_request.labels.*.name }}}
          do
          echo File: $ELEMENT.
          done
          echo ${{ github.event.pull_request.labels.*.name }}

