on: [ push, pull_request ]

jobs:
  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    outputs:
      output1: ${{ steps.info.outputs.data }}
    steps:
      - uses: actions/checkout@v1

      - name: Run read-yaml action
        id: info
        uses: jbutcher5/read-yaml@1.6
        with:
          file: '.github/cicd.yml'
          key-path: '["app", "schedule"]'

      - name: Display read-yaml output
        run: |
          echo "${{ toJson(steps.info.outputs) }}"
