name: Update major and minor tags

on:
  release:
    types: [released]

jobs:
  update_tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: echo ${{ github.event.release.tag_name }}
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
