name: Update major and minor tags

on:
  release:
    types: [released]

jobs:
  update_tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: echo ${{ github.event.release.tag_name }}
      - run: |
          v1=$(echo '${{ github.event.release.tag_name }}' | cut -d '.' -f1)
          v1_0=$(echo '${{ github.event.release.tag_name }}' | cut -d '.' -f1-2)
          echo $v1
          echo $v1_0
      - name: Publish tag
        uses: actions/github-script@v5
        with:
          script: |
            const version = "${{ github.event.release.tag_name }}";
            const major = version.split(".")[0];
            const minor = version.split(".").slice(0, 2).join(".");
            const tag = github.rest.git.getTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              major,
            });
            console.log(JSON.stringify(tag));
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/' + major,
              sha: context.sha
            })
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
