name: Create release

on:
  workflow_dispatch:

jobs:
  create_release:
    uses: ./.github/workflows/yaml_updater.yaml
    with:
      target_repository: target-test
      target_property: "foo.bar.zoz"
      value: 90
      file_path: "foo_bar.yaml"
      commit_message: "foooooo"
