name: YAML Updater

on:
  workflow_call:
    inputs:
      target_repository:
        description: 'Target repository name'
        required: true
        type: string
      target_property:
        description: 'Target property to update'
        required: true
        type: string
      value:
        description: 'Value to set'
        required: true
        type: string
      file_path:
        description: 'File path to update'
        required: true
        type: string
      commit_message:
        description: 'Commit message'
        required: true
        type: string

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: GitOps release
      uses: mknet3/gitops-yaml-release@main
      with:
        target_repository: ${{ inputs.target_repository }}
        target_property: ${{ inputs.target_property }}
        value: ${{ inputs.value }}
        file_path: ${{ inputs.file_path }}
        commit_message: ${{ inputs.commit_message }}
        gh_token: ${{ steps.generate_token.outputs.token }}
