name: YAML Updater

on:
  workflow_dispatch:
    inputs:
      target_repository:
        description: 'Target repository name'
        required: true
      target_property:
        description: 'Target property to update'
        required: true
      value:
        description: 'Value to set'
        required: true
      file_path:
        description: 'File path to update'
        required: true
      commit_message:
        description: 'Commit message'
        required: true

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yq
      run: pip install yq

    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Clone Target Repository
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh repo clone ${{ github.repository_owner }}/${{ inputs.target_repository }}
        cd ${{ inputs.target_repository }}

    - name: Update YAML File
      run: |
        yq e '.${{ inputs.target_property }} = "${{ inputs.value }}"' -i ./${{ inputs.file_path }}

    - name: Commit and Push Changes
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add ./${{ inputs.file_path }}
        git commit -m "${{ inputs.commit_message }}"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository_owner }}/${{ inputs.target_repository }}.git HEAD:main
